#
#  Copyright (c) 2005, LeCroy Corp. - All Rights Reserved
#
#  IE_Colors.inc
#
#  Color definitions for Wireless USB Wire Adapter decoders.
#

###########################################################################
#                              IE color defines                           #
###########################################################################

const IE_Reserved_IE_Color                         = RGB(175,126,194);
const IE_WCTA_IE_Color                             = RGB(175,126,194); 
const IE_WCONNECTACK_IE_Color                      = RGB(175,126,194); 
const IE_WHOSTINFO_IE_Color                        = RGB(175,126,194);
const IE_WCHCHANGEANNOUNCE_IE_Color                = RGB(175,126,194);
const IE_WDEV_DISCONNECT_IE_Color                  = RGB(175,126,194);
const IE_WHOST_DISCONNECT_IE_Color                 = RGB(175,126,194); 
const IE_WRELEASE_CHANNEL_IE_Color                 = RGB(175,126,194); 
const IE_WWORK_IE_Color                            = RGB(175,126,194); 
const IE_WCHANNEL_STOP_IE_Color                    = RGB(175,126,194);
const IE_WDEV_KEEPALIVE_IE_Color                   = RGB(175,126,194); 
const IE_WISOCH_DISCARD_IE_Color                   = RGB(175,126,194); 
const IE_WRESETDEVICE_IE_Color                     = RGB(175,126,194); 
const IE_WXMIT_PACKET_ADJUST_IE_Color              = RGB(175,126,194); 
const IE_ReservedCTA_Color                         = RGB(90, 100, 100); 
const IE_WDRCTA_Color                              = RGB(90, 100, 100); 
const IE_WDTCTA_Color                              = RGB(248, 169, 11); 
const IE_WDNTSCTA_Color                            = RGB(157, 191, 250); 