# VideoCellColors.inc
#
# Contains the declarations of the different colors used in the other .inc files and the .dec files



set HiBandwidthColor = 0x00BABE;
set RegBandwidthColor = 0xBABE00;

set VideoCaptionColor   = 0x0DEFACE;
set VideoIntControlColor = 0x740A0A;
set VideoStreamingColor  = 0x007555;			#This was a typo, should have been VideoIntStreamingColor, duplicate values incase value is used elsewhere;
set VideoIntStreamingColor  = 0x007555;
set VideoBulkInColor     = 0x640A0A;
set VideoBulkOutColor    = 0x783829;
set VideoIsocInColor     = 0x108384;
set VideoIsocOutColor    = 0x802728;


set VideoGetCurRequestColor    = 0x00C060;
set VideoSetCurRequestColor    = 0x00A050;
set VideoGetMinMaxRequestColor = 0x008040;
set VideoGetResRequestColor    = 0x005030;
set VideoGetLenRequestColor    = 0x004020;
set VideoGetInfoRequestColor   = 0x002010;
set VideoGetDefRequestColor    = 0x000000;


set NotFoundBaseColor                   = 0x000000;             
set VideoControlInterfaceBaseColor      = 0x200090;         
set TerminalBaseColor                   = 0x400080;                
set SelectorUnitBaseColor               = 0x600070;         
set CameraBaseColor                     = 0x800060;         
set ProcessingUnitBaseColor             = 0xA00050;               
set ExtensionUnitBaseColor              = 0xC00040;         
set VideoStreamingBaseColor             = 0xE00030;
set EncodingUnitControlSelectorsColor   = 0xF00010;                

