#
#  Copyright (c) 1998 - 2009, Computer Access Technology Corp. - All Rights Reserved
#
#   VSUser_globals.inc
#
#   This file contains user-defined globals( variables and constants ) for 
#   Verification .
#
#
#   Add your own additional definitions here if you need.
#
#######################################################################################


#
# Add your constants here...
#


#
# Add your global variables here...
#